Implement the following:- 
 loc, 
iloc, 
explicit method of filtering
Implicit method filtering
Query method

Objective:
The objective of this exercise is to understand and analyze flight-related data using essential DataFrame methods. The dataset contains parameters related to flight schedules, delays, and cancellations. This lab focuses on exploring and interpreting the data to uncover patterns and insights.
 
 
1. Data Overview
Task: Identify the shape of the dataset (number of rows and columns).
Method: Use a method to get the dimensions of the dataset.
2. Column Information
Task: Display the column names, data types, and non-null values.
Method: Use appropriate methods to describe the dataset structure.
3. Previewing Data
Task: View the first and last few rows of the dataset.
Method: Use methods to display the top and bottom rows of the dataset.
4. Handling Missing Data
Task: Check for missing values in the dataset.
Method: Use methods to identify null values and their counts.
5. Descriptive Statistics
Task: Generate summary statistics for numerical columns, including mean, median, standard deviation, and percentiles.
Method: Use statistical methods to compute descriptive statistics.
6. Filtering Data
Task: Extract records where flights were delayed by more than 15 minutes or were canceled.
Method: Apply filtering techniques on columns like DepDelay, ArrDelay, and Cancelled.
7. Grouping and Aggregation
Task: Analyze the average delay for each airline (Carrier) or by airport.
Method: Use grouping and aggregation methods to summarize the data.
8. Sorting
Task: Sort the dataset by DepDelay in descending order to find the most delayed flights.
Method: Use sorting methods for the analysis

In [1]:
import pandas as pd

In [3]:
Flight_data = pd.read_csv(r"C:\Users\Kavita Pant\Downloads\sample.csv")

In [5]:
Flight_data.shape

(271940, 20)

In [7]:
Flight_data.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'Carrier',
       'OriginAirportID', 'OriginAirportName', 'OriginCity', 'OriginState',
       'DestAirportID', 'DestAirportName', 'DestCity', 'DestState',
       'CRSDepTime', 'DepDelay', 'DepDel15', 'CRSArrTime', 'ArrDelay',
       'ArrDel15', 'Cancelled'],
      dtype='object')

In [4]:
Flight_data

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,2013,9,16,1,DL,15304,Tampa International,Tampa,FL,12478,John F. Kennedy International,New York,NY,1539,4,0.0,1824,13,0,0
1,2013,9,23,1,WN,14122,Pittsburgh International,Pittsburgh,PA,13232,Chicago Midway International,Chicago,IL,710,3,0.0,740,22,1,0
2,2013,9,7,6,AS,14747,Seattle/Tacoma International,Seattle,WA,11278,Ronald Reagan Washington National,Washington,DC,810,-3,0.0,1614,-7,0,0
3,2013,7,22,1,OO,13930,Chicago O'Hare International,Chicago,IL,11042,Cleveland-Hopkins International,Cleveland,OH,804,35,1.0,1027,33,1,0
4,2013,5,16,4,DL,13931,Norfolk International,Norfolk,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,545,-1,0.0,728,-9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271935,2013,9,20,5,VX,13204,Orlando International,Orlando,FL,12892,Los Angeles International,Los Angeles,CA,1730,1,0.0,1945,18,1,0
271936,2013,4,19,5,FL,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,11697,Fort Lauderdale-Hollywood International,Fort Lauderdale,FL,1020,24,1.0,1218,61,1,0
271937,2013,10,26,6,WN,12191,William P Hobby,Houston,TX,10821,Baltimore/Washington International Thurgood Ma...,Baltimore,MD,1540,30,1.0,1935,15,1,0
271938,2013,5,7,2,HA,13830,Kahului Airport,Kahului,HI,12173,Honolulu International,Honolulu,HI,609,-5,0.0,641,-6,0,0
271939,2013,6,11,2,UA,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1338,60,1.0,2200,40,1,0

In [5]:
#View the first and last few rows of the dataset.
Flight_data.head(5)

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,2013,9,16,1,DL,15304,Tampa International,Tampa,FL,12478,John F. Kennedy International,New York,NY,1539,4,0.0,1824,13,0,0
1,2013,9,23,1,WN,14122,Pittsburgh International,Pittsburgh,PA,13232,Chicago Midway International,Chicago,IL,710,3,0.0,740,22,1,0
2,2013,9,7,6,AS,14747,Seattle/Tacoma International,Seattle,WA,11278,Ronald Reagan Washington National,Washington,DC,810,-3,0.0,1614,-7,0,0
3,2013,7,22,1,OO,13930,Chicago O'Hare International,Chicago,IL,11042,Cleveland-Hopkins International,Cleveland,OH,804,35,1.0,1027,33,1,0
4,2013,5,16,4,DL,13931,Norfolk International,Norfolk,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,545,-1,0.0,728,-9,0,0

In [6]:
Flight_data.tail(5)

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
271935,2013,9,20,5,VX,13204,Orlando International,Orlando,FL,12892,Los Angeles International,Los Angeles,CA,1730,1,0.0,1945,18,1,0
271936,2013,4,19,5,FL,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,11697,Fort Lauderdale-Hollywood International,Fort Lauderdale,FL,1020,24,1.0,1218,61,1,0
271937,2013,10,26,6,WN,12191,William P Hobby,Houston,TX,10821,Baltimore/Washington International Thurgood Ma...,Baltimore,MD,1540,30,1.0,1935,15,1,0
271938,2013,5,7,2,HA,13830,Kahului Airport,Kahului,HI,12173,Honolulu International,Honolulu,HI,609,-5,0.0,641,-6,0,0
271939,2013,6,11,2,UA,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1338,60,1.0,2200,40,1,0

In [7]:
#Check for missing values in the dataset.
Flight_data.isnull()

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271935,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
271936,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
271937,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
271938,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
271939,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
#identify null values and their counts
Flight_data.isnull().sum()

Year                    0
Month                   0
DayofMonth              0
DayOfWeek               0
Carrier                 0
OriginAirportID         0
OriginAirportName       0
OriginCity              0
OriginState             0
DestAirportID           0
DestAirportName         0
DestCity                0
DestState               0
CRSDepTime              0
DepDelay                0
DepDel15             2761
CRSArrTime              0
ArrDelay                0
ArrDel15                0
Cancelled               0
dtype: int64

In [9]:
#Task: Generate summary statistics for numerical columns, including mean, median, standard deviation, and percentiles.

In [23]:
mean_value = Flight_data[["CRSDepTime", "DepDelay", "CRSArrTime",  "ArrDelay", "Cancelled"]].mean()
mean_value

CRSDepTime    1325.498713
DepDelay        10.350449
CRSArrTime    1505.477819
ArrDelay         6.496650
Cancelled        0.010723
dtype: float64

In [25]:
median_value = Flight_data[["CRSDepTime", "DepDelay", "CRSArrTime",  "ArrDelay", "Cancelled"]].median()
median_value

CRSDepTime    1320.0
DepDelay        -1.0
CRSArrTime    1529.0
ArrDelay        -3.0
Cancelled        0.0
dtype: float64

In [27]:
standard_deviation_value = Flight_data[["CRSDepTime", "DepDelay", "CRSArrTime",  "ArrDelay", "Cancelled"]].std()
standard_deviation_value

CRSDepTime    470.748546
DepDelay       35.673710
CRSArrTime    493.204020
ArrDelay       38.230331
Cancelled       0.102995
dtype: float64

In [35]:
percentile_value = Flight_data[["CRSDepTime", "DepDelay", "CRSArrTime",  "ArrDelay", "Cancelled"]].quantile(0.25)
percentile_value

CRSDepTime     920.0
DepDelay        -4.0
CRSArrTime    1119.0
ArrDelay       -11.0
Cancelled        0.0
Name: 0.25, dtype: float64

In [37]:
percentile_value1 = Flight_data[["CRSDepTime", "DepDelay", "CRSArrTime",  "ArrDelay", "Cancelled"]].quantile(0.75)
percentile_value1

CRSDepTime    1725.0
DepDelay         9.0
CRSArrTime    1918.0
ArrDelay        10.0
Cancelled        0.0
Name: 0.75, dtype: float64

6. Filtering Data
Task: Extract records where flights were delayed by more than 15 minutes or were canceled.
Method: Apply filtering techniques on columns like DepDelay, ArrDelay, and Cancelled.

In [47]:
Flight_delay_15mins= Flight_data[(Flight_data["DepDel15"] == 1)]
Flight_canceled= Flight_data[(Flight_data["Cancelled"] == 1)]

In [53]:
delayed_or_cancelled =pd.concat([Flight_delay_15mins,Flight_canceled],axis=0)
delayed_or_cancelled

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
3,2013,7,22,1,OO,13930,Chicago O'Hare International,Chicago,IL,11042,Cleveland-Hopkins International,Cleveland,OH,804,35,1.0,1027,33,1,0
5,2013,7,28,7,UA,12478,John F. Kennedy International,New York,NY,14771,San Francisco International,San Francisco,CA,1710,87,1.0,2035,183,1,0
9,2013,5,12,7,UA,12478,John F. Kennedy International,New York,NY,12892,Los Angeles International,Los Angeles,CA,1759,40,1.0,2107,10,0,0
13,2013,7,17,3,AA,11298,Dallas/Fort Worth International,Dallas/Fort Worth,TX,13487,Minneapolis-St Paul International,Minneapolis,MN,2025,95,1.0,2245,90,1,0
16,2013,10,31,4,MQ,11057,Charlotte Douglas International,Charlotte,NC,12953,LaGuardia,New York,NY,1630,28,1.0,1830,26,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271410,2013,8,5,1,WN,14831,Norman Y. Mineta San Jose International,San Jose,CA,10800,Bob Hope,Burbank,CA,1525,0,NaN,1625,0,1,1
271607,2013,6,18,2,EV,14100,Philadelphia International,Philadelphia,PA,13244,Memphis International,Memphis,TN,600,0,NaN,729,0,1,1
271634,2013,5,8,3,AA,11298,Dallas/Fort Worth International,Dallas/Fort Worth,TX,14100,Philadelphia International,Philadelphia,PA,1325,0,NaN,1745,0,1,1
271671,2013,10,8,2,WN,12892,Los Angeles International,Los Angeles,CA,12889,McCarran International,Las Vegas,NV,1440,0,NaN,1540,0,1,1
271885,2013,5,15,3,US,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1059,0,NaN,1918,0,1,1

7. Grouping and Aggregation
Task: Analyze the average delay for each airline (Carrier) or by airport.
Method: Use grouping and aggregation methods to summarize the data.

In [71]:
average_delay_by_origin_airport= Flight_data.groupby(Flight_data.Carrier)["DepDelay"].mean()
average_delay_by_origin_airport

Carrier
9E     9.644689
AA    12.114470
AS     0.711857
B6    12.706523
DL     7.130840
EV    14.031160
F9    10.888355
FL    10.551529
HA     1.334753
MQ    14.797882
OO     7.623694
UA    12.265440
US     4.920037
VX    14.120124
WN    12.597017
YV     8.772345
Name: DepDelay, dtype: float64

8. Sorting
Task: Sort the dataset by DepDelay in descending order to find the most delayed flights.
Method: Use sorting methods for the analysis

In [73]:
delayed_flights = Flight_data.sort_values('DepDelay', ascending=False)
delayed_flights

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
180503,2013,4,3,3,AA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,13303,Miami International,Miami,FL,755,1425,1.0,950,1429,1,0
251813,2013,7,2,2,AA,12889,McCarran International,Las Vegas,NV,11298,Dallas/Fort Worth International,Dallas/Fort Worth,TX,805,1386,1.0,1250,1394,1,0
255631,2013,6,17,1,AA,14771,San Francisco International,San Francisco,CA,11298,Dallas/Fort Worth International,Dallas/Fort Worth,TX,905,1366,1.0,1435,1348,1,0
32883,2013,4,1,1,AA,13871,Eppley Airfield,Omaha,NE,11298,Dallas/Fort Worth International,Dallas/Fort Worth,TX,840,1320,1.0,1045,1301,1,0
121919,2013,4,17,3,AA,14492,Raleigh-Durham International,Raleigh/Durham,NC,13930,Chicago O'Hare International,Chicago,IL,1425,1305,1.0,1535,1440,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114556,2013,5,3,5,AS,15376,Tucson International,Tucson,AZ,14747,Seattle/Tacoma International,Seattle,WA,1445,-24,0.0,1753,-35,0,0
156662,2013,4,2,2,YV,14307,Theodore Francis Green State,Providence,RI,12264,Washington Dulles International,Washington,DC,1912,-27,0.0,2049,-21,0,0
132362,2013,4,11,4,EV,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,11618,Newark Liberty International,Newark,NJ,745,-35,0.0,1000,-6,0,0
7989,2013,5,23,4,EV,11292,Denver International,Denver,CO,10693,Nashville International,Nashville,TN,1943,-52,0.0,2315,-10,0,0
113842,2013,10,11,5,F9,10821,Baltimore/Washington International Thurgood Ma...,Baltimore,MD,14100,Philadelphia International,Philadelphia,PA,1940,-63,0.0,2034,-23,0,0